---
title: Privacy and neighborhood data
author: Frank Muraca
date: '2022-03-15'
slug: []
categories:
  - Neighborhoods
tags:
  - Privacy
---

I'm reading Claire McKay Bowen's excellent book [*Protecting Your Privacy in a Data Driven World*](https://clairemckaybowen.com/book/)about balancing the data needs of researchers and policymakers with the privacy needs of those reflected in the data. The book is an approachable overview of how privacy influences how the federal government shares data. (And great for people without a deep background in stats `r emo::ji("man_raising_hand_light_skin_tone")`). For example, Dr. Bowen shares an anecdote about how Census workers worked with federal officials to identify Japanese citizens and Japanese-descendants prior to internment during WWII. The Census's involvement was legal at the time but is now prohibited by federal regulation. ([More here.](https://exhibits.lib.berkeley.edu/spotlight/census/feature/japanese-americans-in-world-war-ii-and-the-census))

Throughout the book I've thought about past projects where I collected and analyzed neighborhood-level data, often in rural communities. These projects usually involved cleaning publicly available tax parcel data for 300-600 properties, most of which were residential units. The data was ultimately used to help local stakeholders understand trends at a hyperlocal. The goal of these analyses are to help policymakers make informed decisions about where the spend limited resources, and help answer questions such as:

-   Are out-of-town investors buying properties in this neighborhood? What types of homes do they tend to acquire?

-   Have public interventions like code enforcement, home repair programs, or streetscaping projects been effective at changing neighborhood conditions?

-   Would certain blocks be good candidates for a new affordable housing development?

Data is drawn from tax parcel data and supplemented with on-the-ground fieldwork that identifies building conditions, vacancy, and community assets. As these types of projects have become more popular over the past few years, my team and I often discuss how this hyperlocal information should be shared.

*Levels of publicness*

The majority of datapoints we included in these projects were often from local GIS offices, albeit relatively outdated websites. In that sense, our analysis didn't disclose individual identities (like property ownership) any more than what's already provided by county tax assessment offices.

That being said, taking that same data and transforming it into a more digestible data visualization often

In her book, Dr. Bowen describes any individual or organization intent on uncovering identifying information as "data adversaries." They could range from large corporations all the way down to individuals with malicious intent. By transforming hyperlocal data into a more accessible format, how did we make the data more approachable for data adversaries?

*Exploratory versus Narrative-driven*

*Community-driven data and privacy*
